sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - git clone --depth=50 --branch=web-apps-1 git://github.com/jburel/omero-test-infra .omero

script:
  - .omero/app-docker

